function [fitresult, gof] = createFit(lambda, spectrum)
%CREATEFIT(LAMBDA,INT)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : lambda
%      Y Output: int
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Feb-2017 14:28:55


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData(lambda, spectrum);

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Lower = [-Inf -Inf 0];
%opts.StartPoint = [67.603 332 16.5572581967461];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


